version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: rewear_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rewear_secure_password
      POSTGRES_DB: rewear_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rewear_backend
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 5000
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:rewear_secure_password@postgres:5432/rewear_db?schema=public"
      JWT_SECRET: "rewear_production_jwt_secret_key_min_32_characters"
      CLIENT_URL: "http://localhost:5173"
      SERVER_URL: "http://localhost:5000"
    ports:
      - "5000:5000"
    volumes:
      - server_uploads:/app/uploads

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rewear_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  postgres_data:
  server_uploads:
