// Seeded realistic fallback data for static GitHub Pages hosting
export const MOCK_USERS = [
  {
    id: 'user-priya',
    name: 'Priya Sharma',
    email: 'priya@rewear.org',
    role: 'USER',
    city: 'Hyderabad',
    state: 'Telangana',
    bio: 'Slow fashion advocate & vintage collector. Love swapping jackets & handloom kurtas!',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    swapCount: 8,
  },
  {
    id: 'user-rahul',
    name: 'Rahul Verma',
    email: 'rahul@rewear.org',
    role: 'USER',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    bio: 'Streetwear fan trying to build a zero-waste wardrobe. Hit me up for hoodies & denim.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    swapCount: 6,
  },
  {
    id: 'user-ananya',
    name: 'Ananya Patel',
    email: 'ananya@rewear.org',
    role: 'USER',
    city: 'Mangalagiri',
    state: 'Andhra Pradesh',
    bio: 'Textile enthusiast living in the handloom capital. Swapping authentic sarees & kurtas.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    rating: 5.0,
    swapCount: 12,
  },
  {
    id: 'user-admin',
    name: 'ReWear Admin',
    email: 'admin@rewear.org',
    role: 'ADMIN',
    city: 'Hyderabad',
    state: 'Telangana',
    bio: 'Platform administrator ensuring fair swaps and sustainable community standards.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 5.0,
    swapCount: 15,
  },
];

export const MOCK_CLOTHES = [
  {
    id: 'item-1',
    title: "Levi's Classic Sherpa Denim Trucker Jacket",
    description: "Timeless trucker jacket with soft fleece lining and copper buttons. Worn only a few times during winter trips. In mint condition.",
    category: 'Jackets',
    brand: "Levi's",
    size: 'M',
    color: 'Indigo Blue',
    material: 'Denim & Fleece',
    condition: 'LIKE_NEW',
    purchaseAge: '< 6 months',
    estimatedValue: 2400,
    originalPrice: 4999,
    exchangePreferences: 'Looking for a warm oversized hoodie or bomber jacket',
    city: 'Hyderabad',
    state: 'Telangana',
    ownerId: 'user-priya',
    owner: MOCK_USERS[0],
    images: [{ url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-2',
    title: 'FabIndia Hand-Block Printed Chanderi Kurta',
    description: 'Elegant flared Chanderi silk-cotton kurta with zari detailing on the neckline. Perfect for festivals and celebrations.',
    category: 'Kurtas',
    brand: 'FabIndia',
    size: 'S',
    color: 'Emerald Green',
    material: 'Chanderi Silk',
    condition: 'EXCELLENT',
    purchaseAge: '6-12 months',
    estimatedValue: 1450,
    originalPrice: 2890,
    exchangePreferences: 'Handloom sarees or linen tops',
    city: 'Hyderabad',
    state: 'Telangana',
    ownerId: 'user-priya',
    owner: MOCK_USERS[0],
    images: [{ url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-3',
    title: 'H&M Heavyweight Oversized Cotton Hoodie',
    description: 'Boxy streetwear silhouette in 450 GSM French Terry cotton. Clean ribbed cuffs and kangaroo pouch. Minimalist staple.',
    category: 'Hoodies',
    brand: 'H&M',
    size: 'L',
    color: 'Sage Green',
    material: 'Organic Cotton',
    condition: 'EXCELLENT',
    purchaseAge: '6-12 months',
    estimatedValue: 1350,
    originalPrice: 2299,
    exchangePreferences: 'Denim trucker jacket or straight fit jeans',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    ownerId: 'user-rahul',
    owner: MOCK_USERS[1],
    images: [{ url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-4',
    title: 'Authentic Mangalagiri Handloom Pure Cotton Saree',
    description: 'Woven locally in Mangalagiri with 80s count pure combed cotton. Features a gleaming Nizam zari border and contrasting mustard pallu.',
    category: 'Sarees',
    brand: 'Mangalagiri Handlooms',
    size: 'Free Size',
    color: 'Royal Maroon & Gold',
    material: 'Organic Cotton',
    condition: 'NEW_WITH_TAGS',
    purchaseAge: '< 6 months',
    estimatedValue: 2600,
    originalPrice: 3800,
    exchangePreferences: 'Silk sarees or festive kurtas',
    city: 'Mangalagiri',
    state: 'Andhra Pradesh',
    ownerId: 'user-ananya',
    owner: MOCK_USERS[2],
    images: [{ url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-5',
    title: 'Uniqlo U Crew Neck Relaxed T-Shirt',
    description: 'Durable compact cotton jersey with structured collar that never loses shape. Clean streetwear essential.',
    category: 'T-Shirts',
    brand: 'Uniqlo',
    size: 'L',
    color: 'Off White',
    material: 'Cotton',
    condition: 'NEW_WITH_TAGS',
    purchaseAge: '< 6 months',
    estimatedValue: 800,
    originalPrice: 1290,
    exchangePreferences: 'Sportswear or casual caps/tees',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    ownerId: 'user-rahul',
    owner: MOCK_USERS[1],
    images: [{ url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-6',
    title: 'Zara Flowy Tiered Midi Summer Dress',
    description: 'Airy viscose tiered dress with ruffle straps and square neckline. Super breathable for sunny days.',
    category: 'Dresses',
    brand: 'Zara',
    size: 'M',
    color: 'Terracotta Floral',
    material: 'Viscose / Rayon',
    condition: 'LIKE_NEW',
    purchaseAge: '< 6 months',
    estimatedValue: 1600,
    originalPrice: 3290,
    exchangePreferences: 'Denim skirts or formal trousers',
    city: 'Hyderabad',
    state: 'Telangana',
    ownerId: 'user-priya',
    owner: MOCK_USERS[0],
    images: [{ url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-7',
    title: "Levi's 511 Slim Fit Selvedge Jeans",
    description: 'Raw indigo Japanese selvedge denim. Beautiful honeycombs forming naturally. Authentic red selvedge line inside hem.',
    category: 'Jeans',
    brand: "Levi's",
    size: '32',
    color: 'Raw Indigo',
    material: 'Denim',
    condition: 'EXCELLENT',
    purchaseAge: '1-2 years',
    estimatedValue: 1850,
    originalPrice: 4200,
    exchangePreferences: 'Utility cargo pants, leather accessories, or light jackets',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    ownerId: 'user-rahul',
    owner: MOCK_USERS[1],
    images: [{ url: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'item-8',
    title: 'Allen Solly Slim Fit Wrinkle-Resistant Formal Shirt',
    description: '100% Egyptian giza cotton twill weave shirt. Crisp spread collar, mother of pearl buttons.',
    category: 'Shirts',
    brand: 'Allen Solly',
    size: '40',
    color: 'Sky Blue',
    material: 'Cotton',
    condition: 'LIKE_NEW',
    purchaseAge: '< 6 months',
    estimatedValue: 1100,
    originalPrice: 2199,
    exchangePreferences: 'Linen casual shirts or polo t-shirts',
    city: 'Guntur',
    state: 'Andhra Pradesh',
    ownerId: 'user-priya',
    owner: MOCK_USERS[0],
    images: [{ url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80' }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  }
];

// Add additional realistic items to round out full 20+ clothes
const moreBrands = ['Zara', 'FabIndia', "Levi's", 'H&M', 'Nike', 'Mango', 'Marks & Spencer'];
const moreCats = ['Jackets', 'Kurtas', 'Sarees', 'Hoodies', 'Jeans', 'Dresses', 'Sportswear'];
const moreImgs = [
  'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600',
  'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600',
  'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600',
  'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600',
  'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600',
  'https://images.unsplash.com/photo-1548883354-7622d03aca27?w=600',
];

for (let i = 9; i <= 24; i++) {
  const brand = moreBrands[i % moreBrands.length];
  const cat = moreCats[i % moreCats.length];
  const owner = MOCK_USERS[i % MOCK_USERS.length];
  MOCK_CLOTHES.push({
    id: `item-${i}`,
    title: `${brand} Curated ${cat.slice(0, -1) || cat}`,
    description: `Gently loved authentic ${brand} garment in pristine condition. Zero defects, stored in smoke-free home.`,
    category: cat,
    brand,
    size: 'M',
    color: 'Classic Earthy',
    material: 'Organic Cotton',
    condition: 'LIKE_NEW',
    purchaseAge: '< 6 months',
    estimatedValue: 1200 + ((i * 110) % 1500),
    originalPrice: 2800,
    exchangePreferences: 'Open to trades for equivalent quality clothes',
    city: owner.city,
    state: owner.state,
    ownerId: owner.id,
    owner,
    images: [{ url: moreImgs[i % moreImgs.length] }],
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
  });
}
